sonar.projectKey=vrunsys_mern-auth-service
sonar.organization=vrunsys

sonar.projectName=mern-auth-service
sonar.sources=src

sonar.tests=tests

sonar.exclusions=**/node_modules/**/*, **/dist/**/*, **/build/**/*

sonar.qualitygate.wait=true

sonar.javascript.lcov.reportPaths=./coverage/lcov.info

sonar.scm.exclusions.disabled=true