const {
	PORT,
	NODE_ENV,
	DATABASE_URL,
	REFRESH_TOKEN_SECRET,
	JWT_URI,
	PRIVATE_KEY,
	ADMIN_EMAIL,
	ADMIN_PASSWORD,
	ADMIN_FIRST_NAME = "System",
	ADMIN_LAST_NAME = "Administrator",
} = process.env;

export const config = {
	PORT: PORT,
	NODE_ENV: NODE_ENV,
	DATABASE_URL: DATABASE_URL,
	REFRESH_TOKEN_SECRET: REFRESH_TOKEN_SECRET!,
	JWT_URI: JWT_URI,
	PRIVATE_KEY: PRIVATE_KEY!,
	ADMIN_EMAIL,
	ADMIN_PASSWORD,
	ADMIN_FIRST_NAME,
	ADMIN_LAST_NAME,
};
