const {
	PORT,
	NODE_ENV,
	DATABASE_URL,
	REFRESH_TOKEN_SECRET,
	JWT_URI,
	PRIVATE_KEY,
} = process.env;

export const config = {
	PORT: PORT,
	NODE_ENV: NODE_ENV,
	DATABASE_URL: DATABASE_URL,
	REFRESH_TOKEN_SECRET: REFRESH_TOKEN_SECRET!,
	JWT_URI: JWT_URI,
	PRIVATE_KEY: PRIVATE_KEY!,
};
